version: '2'
services:
  web:
    build: .
    container_name: ispconfig
    restart: always
    volumes:
#      - ./var/www/html:/var/www/html
      - db-data:/var/lib/mysql
    environment:
      - DB_NAME=lemp_bdd
      - TABLE_PREFIX=lemp_
      - DB_HOST=lemp
      - DB_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MAILMAN_EMAIL_HOST=test.com
      - MAILMAN_EMAIL=test@test.com
      - MAILMAN_PASS=password
    ports:
          - 21:21
          - 22:22
          - 80:80
          - 443:443
          - 3306:3306
          - 8080:8080
volumes:
  db-data:
    driver: local
#networks:
#    default:
#        driver: bridge